backend:
  name: github
  repo: OlaJurrek/minorities
  branch: main

publish_mode: editorial_workflow

locale: 'pl'

media_folder: static/uploads
public_folder: /uploads

collections:
  #----------------------PL------------------------
  #--------- Strony mniejszości - PL --------------
  - name: minoritiesPL
    label: Strony mniejszości - PL
    folder: 'src/content/pl/minorities'
    label_singular: strona mniejszości
    identifier_field: path
    preview_path: '{ { path } }'
    summary: '{{title}} {{titleAddition}}'
    create: true
    fields:
      - { name: type, label: 'Typ', widget: hidden, default: 'single-minority' }
      - {
          name: path,
          label: 'Ostatnia część ścieżki do strony',
          hint: 'Musi być taka sama dla obu języków - identyfikuje strony przy zmianie języka. Nie używaj diakretyków, wielkich liter ani spacji, pojedyncze słowa łącz myślnikami, np. czesi-w-polsce',
          widget: string,
          pattern:
            [
              '^[a-z]+(-[a-z]+)*$',
              'tylko małe litery, bez spacji, bez diakretyków',
            ],
        }
      - { name: title, label: 'Nazwa mniejszości', widget: string }
      - {
          name: titleAddition,
          label: 'Dodatek do nazwy mniejszości',
          widget: string,
          hint: 'Np. lokalizacja geograficzna mniejszości',
          required: false,
        }
      - {
          name: body,
          label: 'Główna treść',
          widget: markdown,
          hint: 'Jeśli potrzebujesz użyć nagłówków, zacznij od poziomu 2',
        }
      - { name: image, label: Obrazek, required: false, widget: image }

  - name: pagesPL
    label: Pozostałe strony - PL
    media_folder: './../media/'
    public_folder: ''
    files:
      #----- O projekcie - PL -------
      - file: 'src/content/pl/o-projekcie.md'
        label: 'O projekcie'
        name: 'aboutPL'
        preview_path: o-projekcie
        fields:
          - { name: type, label: 'Typ', widget: hidden, default: about }
          - { label: 'Główny nagłówek', name: title, widget: string }
          - {
              label: 'Opis projektu',
              name: body,
              widget: markdown,
              hint: 'Jeśli potrzebujesz użyć nagłówków, zacznij od poziomu 2',
            }
          - {
              label: 'Nagłówek terminów spotkań',
              name: 'datesHeader',
              widget: string,
            }
          - {
              name: 'dates',
              label: 'Terminy spotkań',
              required: false,
              widget: 'list',
              label_singular: 'termin spotkania',
              default: [],
              field:
                { label: 'spotkanie', name: 'Spotkanie', widget: 'string' },
            }
          - {
              name: patron1,
              label: 'Logo pierwszego patrona',
              required: false,
              widget: image,
            }
      #----- O mniejszościach i większościach - PL -------
      - file: 'src/content/pl/erazim-kohak.md'
        label: 'O mniejszościach i większościach'
        name: 'translated-articlePL'
        preview_path: erazim-kohak
        fields:
          - { name: type, label: Typ, widget: hidden, default: article }
          - { label: Autor, name: author, widget: string }
          - { label: Tytuł, name: title, widget: string }
          - {
              label: Główna treść,
              name: body,
              widget: markdown,
              hint: 'Jeśli potrzebujesz użyć nagłówków, zacznij od poziomu 2',
            }
          - {
              name: translator,
              label: Tłumacz,
              widget: string,
              required: false,
              default: '',
            }

  #----------------------CZ------------------------
  #--------- Strony mniejszości - CZ --------------
  - name: minoritiesCZ
    label: Stránky menšin - CZ
    folder: 'src/content/cz/minorities'
    label_singular: stránka menšiny
    identifier_field: path
    preview_path: 'cz/{{path}}'
    summary: '{{title}} {{titleAddition}}'
    create: true
    fields:
      - {
          name: path,
          label: 'Poslední část adresu stránky',
          hint: 'Musí být stejná pro oba jazyky - identifikuje stránky při změně jazyka. Nepoužívej diakritiku, velká písmena a mezery, jednotlivá slova spojuj pomlčkou, např. czesi-w-polsce',
          widget: string,
          pattern:
            [
              '^[a-z]+(-[a-z]+)*$',
              'pouze malá písmena, bez mezer a diakritiky',
            ],
        }
      - { name: title, label: Název menšiny, widget: string }
      - {
          name: titleAddition,
          label: 'Dodatek ke názvu',
          widget: string,
          hint: 'Např. geografická lokalizace menšiny',
          required: false,
        }
      - { name: type, label: Type, widget: hidden, default: 'single-minority' }
      - {
          name: body,
          label: Hlavní obsah,
          widget: markdown,
          hint: 'Pokud potřebuješ použít nadpis, začni od 2. úrovně',
        }
      - { name: image, label: Obrázek, required: false, widget: image }

  - name: pagesCZ
    label: Ostatní stránky - CZ
    files:
      #--------- O projekcie - CZ ----------------
      - file: 'src/content/cz/o-projekcie.md'
        label: 'O projektě'
        name: 'aboutCZ'
        preview_path: cz/o-projekcie
        fields:
          - { name: type, label: Type, widget: hidden, default: about }
          - { label: 'Hlavní nadpis', name: title, widget: string }
          - {
              label: 'Popis projektu',
              name: body,
              widget: markdown,
              hint: 'Pokud potřebuješ použít nadpis, začni od 2. úrovně',
            }
          - {
              label: 'Nadpis termínů setkání',
              name: 'datesHeader',
              widget: string,
            }
          - {
              name: 'dates',
              label: 'Termíny setkání',
              required: false,
              widget: 'list',
              label_singular: 'termín setkání',
              default: [],
              field: { label: 'spotkanie', name: 'Setkání', widget: 'string' },
            }
          - {
              name: patron1,
              label: 'Logo první organizace',
              required: false,
              widget: image,
            }
      #----- O mniejszościach i większościach - CZ -------
      - file: 'src/content/cz/erazim-kohak.md'
        label: 'Většiny, mešiny'
        name: 'translated-articleCZ'
        preview_path: cz/erazim-kohak
        fields:
          - { name: type, label: Type, widget: hidden, default: article }
          - { label: Autor, name: author, widget: string }
          - { label: Název, name: title, widget: string }
          - {
              label: Hlavní obsah,
              name: body,
              widget: markdown,
              hint: 'Pokud potřebuješ použít nadpis, začni od 2. úrovně',
            }
          - {
              name: translator,
              label: Překladatel,
              widget: string,
              required: false,
              default: '',
            }
