backend:
  name: github
  repo: OlaJurrek/minorities
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: minorities
    label: Strony mniejszości
    label_singular: strona mniejszości
    folder: "src/content/minorities"
    slug: "{{path}}"
    create: true
    fields:
      - {
          name: path,
          label: "Ostatnia część ścieżki do strony",
          hint: "Np. mniejszosci-w-polsce",
          widget: string,
        }
      - { name: title, label: "Nazwa mniejszości", widget: string }
      - {
          name: titleAddition,
          label: "Dodatek do nazwy mniejszości",
          widget: string,
          hint: "Np. lokalizacja geograficzna mniejszości",
          required: false,
        }
      - { name: type, label: "Typ", widget: hidden, default: "single-minority" }
      - { name: body, label: "Główna treść", widget: markdown }
      - { name: image, label: Obrazek, required: false, widget: image }

  - name: pages
    label: Pozostałe strony
    files:
      - file: "src/content/about.md"
        label: "O projekcie"
        name: "about"
        fields:
          - { label: "Główny nagłówek", name: title, widget: string }
          - { label: "Opis projektu", name: body, widget: markdown }
          - {
              label: "Nagłówek terminów spotkań",
              name: "dates-header",
              widget: string,
            }
          - {
              name: "dates",
              label: "Terminy spotkań",
              required: false,
              widget: "list",
              label_singular: "termin spotkania",
              default: ["dates"],
              field:
                { label: "spotkanie", name: "Spotkanie", widget: "string" },
            }
          - {
              name: patrons,
              label: "Loga patronów",
              required: false,
              widget: list,
              label_singular: "logo",
              field: { name: logo, label: Logo, widget: image },
            }
      - file: "src/content/translated-article.md"
        label: "O mniejszościach i większościach"
        name: "translated-article"
        fields:
          - { label: "Autor", name: "author", widget: string }
          - { label: "Tytuł", name: "title", widget: string }
          - { label: "Główna treść", name: body, widget: markdown }
          - {
              name: translator,
              label: "Tłumacz",
              widget: string,
              required: false,
            }

  - name: settings
    label: "Pozostałe teksty"
    delete: false
    files:
      - name: "title"
        label: "Tytuł projektu"
        file: "src/content/metadata.json"
        fields:
          - { name: "title_pl", label: "Polski tytuł", widget: string }
          - { name: "title_cz", label: "Czeski tytuł", widget: string }
